# Generated by Django 4.0.4 on 2022-06-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(blank=True, max_length=30, null=True)),
                ('stop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stop_lat', models.FloatField(blank=True, null=True)),
                ('stop_long', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stops',
                'managed': False,
            },
        ),
    ]
