# Generated by Django 4.0.4 on 2022-06-22 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtfsAPI', '0002_shapes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shapes',
        ),
    ]
