# Generated by Django 4.0.5 on 2022-07-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfsAPI', '0003_delete_shapes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('stop_id', models.CharField(blank=True, max_length=30, primary_key=True, serialize=False)),
                ('route_short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('direction_id', models.IntegerField(blank=True, null=True)),
                ('stop_sequence', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'route_stops',
                'managed': False,
            },
        ),
    ]
