# Generated by Django 4.0.5 on 2022-07-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfsAPI', '0004_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('route_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('agency_id', models.CharField(max_length=10)),
                ('route_short_name', models.CharField(max_length=10)),
                ('route_long_name', models.CharField(max_length=255)),
                ('route_type', models.IntegerField()),
            ],
            options={
                'db_table': 'routes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('arrival_time', models.TimeField(primary_key=True, serialize=False)),
                ('departure_time', models.TimeField()),
                ('stop_sequence', models.IntegerField()),
                ('stop_headsign', models.CharField(max_length=255)),
                ('pickup_type', models.IntegerField()),
                ('drop_off_type', models.IntegerField()),
                ('shape_dist_traveled', models.FloatField()),
            ],
            options={
                'db_table': 'stop_times',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('shape_id', models.CharField(max_length=30)),
                ('trip_headsign', models.CharField(max_length=255)),
                ('direction_id', models.IntegerField()),
                ('service_id', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'trips',
                'managed': False,
            },
        ),
    ]
