# Generated by Django 4.0.4 on 2022-07-07 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtfsAPI', '0005_stoptimes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stoptimes',
            options={'managed': False},
        ),
    ]
