# Generated by Django 4.0.4 on 2022-07-07 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtfsAPI', '0006_alter_stoptimes_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stoptimes',
            table='stop_times',
        ),
    ]
