# Generated by Django 4.0.5 on 2022-07-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtfsAPI', '0005_routes_stoptime_trip'),
        ('gtfsAPI', '0007_alter_stoptimes_table'),
    ]

    operations = [
    ]
