# Generated by Django 4.0.4 on 2022-07-28 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userManagement', '0002_alter_user_data_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='user_data',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
