# Generated by Django 4.0.4 on 2022-08-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0003_remove_user_data_user_id_alter_user_data_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='name_1',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='name_2',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='name_3',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
