# Generated by Django 4.0.4 on 2022-08-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0004_user_data_name_1_user_data_name_2_user_data_name_3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='name_1',
            new_name='favourite_stop_1_name',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='name_2',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='name_3',
        ),
    ]
