# Generated by Django 4.0.4 on 2022-08-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0005_rename_name_1_user_data_favourite_stop_1_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='favourite_stop_2_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='favourite_stop_3_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
