# Generated by Django 4.0.4 on 2022-08-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0006_user_data_favourite_stop_2_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='favourite_stop_1_name',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='favourite_stop_2_name',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='favourite_stop_3_name',
        ),
    ]
